name: sosansheaven
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  http: ^1.2.2
  shared_preferences: ^2.2.0
  flutter_admin_scaffold: ^1.4.0
  fluttertoast: ^8.2.8


dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  footer: ^0.0.4
  flutter_screenutil: ^5.9.3


flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
     - family: appfont
       fonts:
         - asset: fonts/kinn-heavy.ttf

